const products = [
    {id: "4", title: "Iphone 13 Pro", category:"Iphone", price: 1500, img:"https://www.pngmart.com/files/21/iPhone-13-Pro-PNG-Image.png" , stock: 8, description:"La pantalla del iPhone 13 Pro tiene esquinas redondeadas que siguen el elegante diseño curvo del teléfono, y las esquinas se encuentran dentro de un rectángulo estándar. Si se mide en forma de rectángulo estándar, la pantalla tiene 6.06 pulgadas en diagonal (el área real de visualización es menor)."},
    {id: "2", title: "Samsung Z Flip 5", category:"Samsung", price: 614999, img:"https://i.blogs.es/42d73e/samsung-galaxy-z-flip-filtracion-detalle-diseno/1366_2000.png" , stock: 4, description:"No te pierdas de un solo momento con el nuevo Samsung Galaxy Z Flip5. Con su cámara de 12+12 MP; sacá fotos nítidas y claras tanto de día como de noche. El Samsung Galaxy Z Flip5 posee un procesador Octa-Core (3.36GHz,2.8GHz,2GHz) para que disfrutes de todas tus aplicaciones sin inconvenientes. Memoria interna de 512 GB"},
    {id: "7", title: "Motorola Razr 40 Ultra", category:"Motorola", price: 649999, img:"https://armoto.vtexassets.com/arquivos/ids/164681-800-auto?v=638241762208330000&width=800&height=auto&aspect=true" , stock: 2, description:'Diseño exclusivo con pantalla flexible de 6.9” y bisagra “gota” sin espacios entre sus lados.'},
    {id: "8", title: "Moto G72", category:"Motorola", price: 179999, img:"https://armoto.vtexassets.com/arquivos/ids/163878-800-auto?v=638082338261870000&width=800&height=auto&aspect=true" , stock: 2, description:'El Moto G72 es un nuevo móvil de gama media con conectividad 4G que incorpora mejoras importantes como la nueva pantalla OLED a 120 Hz o la cámara triple cuyo sensor principal es de 108 megapíxeles.'},
    {id: "6", title: "Iphone 14 Pro Max", category:"Iphone", price: 1500, img:"https://outtec.com.ar/wp-content/uploads/2023/05/61HHS0HrjpL._AC_SL1500_-jpg.webp" , stock: 2, description:"Descripcion del Iphone 14 Pro Max de 128 gb. Modelo 2023"},
    {id: "1", title: "Samsung S23", category:"Samsung", price: 755999, img:"https://www.centrogar.com.ar/13938-thickbox_default/celular-samsung-s23-256gb-verde-sm-s911bzgm.jpg", stock: 6, description:"El Samsung Galaxy S23 llega con algunos cambios de diseño y upgrades incrementales sobre su predecesor. Con una pantalla Dynamic AMOLED 2X de 6.1 pulgadas con tasa de refresco de 120Hz, resolución FHD+ y vidrio Gorilla Glass Victus 2, el Galaxy S23 está potenciado por un procesador Snapdragon 8 Gen 2 for Galaxy, una variante del chip de Qualcomm que corre a 3.36GHz, junto con 8GB de RAM y hasta 512GB de almacenamiento interno."},
    {id: "5", title: "Iphone 12", category:"Iphone", price: 900, img:"https://i5.walmartimages.com/seo/Straight-Talk-Apple-iPhone-12-64GB-Black-Prepaid-Smartphone-Locked-to-Straight-Talk_66b2853b-6cb5-4f20-b73a-b60b39b6de44.6b3bf83a920058a47342318925f1dc2b.jpeg" , stock: 3, description:"El iPhone 12 tiene el chip A14 Bionic, el más rápido en un smartphone. Una pantalla OLED de borde a borde. Un nuevo frente de Ceramic Shield, cuatro veces más resistente a las caídas. Además, ahora el modo Noche viene en todas las cámaras. El iPhone 12 lo tiene todo. Y está disponible en dos tamaños perfectos."},
    {id: "9", title: "Moto E32", category:"Motorola", price: 67999, img:"https://armoto.vtexassets.com/arquivos/ids/162569-800-auto?v=638097504617530000&width=800&height=auto&aspect=true" , stock: 2, description:'Con un diseño elegante y resistente, el nuevo moto e32 te da el estilo que querés. Viví una experiencia visual fluida con la pantalla HD+ de 6.5" y 90 Hz. Potenciá tu creatividad usando el sistema de triple cámara con IA y enfoque rápido. Además, obtené un procesador potente y una batería duradera de 5000 mAh.'},
    {id: "3", title: "Samsung Z Fold 5", category:"Samsung", price: 1049999, img:"https://www.clarin.com/img/2023/07/26/ArDmJM-8p_720x0__1.jpg" , stock: 1, description:"El Samsung Galaxy Z Fold 5 es la quinta generación del smartphone plegable tipo tablet de Samsung, refinando sobre anteriores generaciones con un nuevo mecanismo de pliegue. El Galaxy Z Fold 5 cuenta con una pantalla interna AMOLED de 7.6 pulgadas con tasa de refresco variable de 120Hz, y una pantalla cover AMOLED de 6.2 pulgadas protegida por vidrio Gorilla Glass Victus 2"},
];

export const myPromise = new Promise((resolve, rejected)=> {
    setTimeout(()=> {
        if (products) {
            resolve(products)
        } else {
            rejected("Algo salio re mal")
        }
    }, 2000)
})